language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

dist: precise
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
